// Secrets and vars supplied through .dev.vars locally and `wrangler secret` in production.
// Merged into the binding types generated by `wrangler types`.
interface Env {
  OPENAI_API_KEY?: string;
  OPENAI_REALTIME_MODEL?: string;
  OPENAI_REALTIME_VOICE?: string;
}
